### PR TITLE
plot to nvme first and pool plotting

### LINKED ISSUE #74: Plot to NVMEs first
Add logic that NVMes are plotted to first.

### LINKED ISSUE #78: Add support for pool plotting
param for plots create: `-c`
for singleton puzzlehash (plotnft, p2singletonaddress) using `chia plotnft show`

user needs to create plotnft first. Either in GUI or with `chia plotnft create -u %pooladdress:80%`, choose wallet key and confirm. 

Later on, that singleton can be altered to point to a new pooladress, so you can keep your plots and move freely to another pool. 
potential CLI command to change: `chia plotnft change`

### PR DESCRIPTION
**Pull request by tydeno**
## Added
* Ability to pass -c param to Chia plots create
Be advised, this is a beta. It is based on the demo we saw from Mariano at the pool operators call. Might not be working correctly yet. closes #78 
* Ploto now checks for NVMEs to spawn the jobs on. If an NVME is found and defined as a TempDrive, it will be used first to spawn a plot on. closes #74 

## Changed
* Added an additional check for OutDrives, if they have JobsinProgress.

## Removed
* ProgressBar for PlotoMover using Bits

### CODE REVIEW

**Comment by realdevnullius** [comment]
I've looked around but wtf is the c-option in `Ability to pass -c parameter to Chia plots create`? :)

**Comment by tydeno** [comment]
We will usa that param to create portable pool plots once they are available.

**Comment by tydeno** [comment]
Testing showed nothing to break. Disclaimer: -c param is still untested.

**Comment by realdevnullius** [comment]
are there portable pools released yet?

**Comment by tydeno** [comment]
> are there portable pools released yet?

Sadly not. We need to wait for chia devteam releasing it to mainnet. You may create portable plots on testnet. But those won't be usable on testnet (missing singleton).

**Pull request merged**
